shutdown mongod with pkill as an alternative

diff --git a/bin/ego b/bin/ego
--- a/bin/ego
+++ b/bin/ego
@@ -777,15 +777,12 @@ stop_mongodb() {
 
     _set_mongod_vars
 
-    # Start Mongod
+    # Stop MongoD
     echo "Stopping MongoDB on port $1..."
-    "$MONGO" admin --port "$1" --eval "db.shutdownServer()"
-    # shellcheck disable=SC2009
-    ps -ef | grep "mongod --port $1" | grep -v grep | awk '{ print $2 }' | xargs -r kill -9
+    "$MONGO" admin --port "$1" --eval "db.shutdownServer()" ||  pkill -f "mongod.*$1" || echo "Failed to stop mongod on port $1" >&2
 
-    echo "Polling MongoD in 5 second intervals..."
-    while "$MONGO" --port "$1" --eval "db.hostInfo()" > /dev/null 2>&1 ; do echo '.'; sleep 5; done;
-    echo "MongoD has stopped running!"
+    wait_for_closed_local_port "$1"
+    echo "MongoDB has stopped running!"
 }
 
 # #######################################################
