fix small naming issue

diff --git a/bin/ego b/bin/ego
--- a/bin/ego
+++ b/bin/ego
@@ -779,7 +779,7 @@ stop_mongodb() {
 
     # Stop MongoD
     echo "Stopping MongoDB on port $1..."
-    "$MONGO" admin --port "$1" --eval "db.shutdownServer()" ||  pkill -f "mongod.*$1" || echo "Failed to stop mongod on port $1" >&2
+    "$MONGO" admin --port "$1" --eval "db.shutdownServer()" ||  pkill -f "mongod.*$1" || echo "Failed to stop MongoDB on port $1" >&2
 
     wait_for_closed_local_port "$1"
     echo "MongoDB has stopped running!"
